export const FETCHING = "FETCHING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_ELIMINATE = "FETCH_ELIMINATE";
export const FETCH_CREATE = "FETCH_CREATE";
